{{- if .Values.route.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.route.name }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
spec:
  hostnames:
  {{- range .Values.route.hostnames }}
  - {{ . | quote }}
  {{- end }}
  parentRefs:
  {{- range .Values.route.parents }}
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .name }}
    namespace: {{ .namespace }}
    sectionName: mpaflask
  {{- end }}
  rules:
  - backendRefs:
    - kind: Service
      name: {{ .Values.svc.name }}
      port: {{ .Values.svc.port }}
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
{{- end -}}
