apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
  labels:
    {{ include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.svc.port }}
      targetPort: {{ .Values.pod.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.pod.name }}
    version: {{ .Chart.AppVersion }}
