#
# Main workflow to build

name: Build

#
# Operational Variables

env:
  MAJOR: 0
  MINOR: 0
  PYTHON_VERSION: 3.9.6

#
# Establish when the workflow is run

on:
  push:
    branches-ignore:
    - main
  pull_request: {}

#
# Workflow

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Pipeline Debugging
      run: |
        env

    - name: Checkout out our code
      uses: actions/checkout@v2

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Establish a cache for dependencies
      uses: actions/cache@v2
      with:
        path: ~/.local
        key: ${{ runner.os }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user wheel
        pip install --user -r requirements.txt
        pip install --user -r test-requirements.txt

    - name: Lint
      run: |
        flake8 --statistics
        pylint mrmat_python_api_flask

    - name: Test
      run: |
        python ./setup.py install
        python -m pytest

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: tests
        path: build/junit.xml

    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: build/coverage.xml
